config/routes.rb
FastLearningApp::Application.routes.draw do
 
  root                            to: 'application_pages#show', :id => 1
  
  match '/home',                  to: 'application_pages#show', :id => 1
  match '/about',                 to: 'application_pages#show', :id => 2
  match '/terms',                 to: 'application_pages#show', :id => 3

  resources :pages
 
  resources :application_pages

  devise_scope :user do
    match "/signin",  :to => "devise/sessions#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
  devise_for :users, :controllers => { :confirmations => "confirmations" }
  
  
  resources :users
  match '/profile', to: 'users#show'
  
  resources :roles

  resources :courses  
  resources :classrooms, except: [:show] do
    match ':id(.:format)',  to: 'classrooms#show', as: :page, via: :get
  end

  resources :resources
  
  resources :enrollments
  
  resources :orders
  
  resources :products
  
  resources :learning_plans
  
  resources :organizations, :path => '' do
    resources :users, :as => 'people',
    :only => [:new, :create],
    :path => 'people',
    :controller => 'organizations/people'
    
  end
  
  resources :learning_spaces, :only => [:index, :new, :create], :path => '/:organization_id/learningspaces/'
  resources :learning_spaces, :only => [:edit, :show, :update, :destroy], :path => '/:organization_id/' do
    resources :users, :as => 'people',
    :only => [:new, :create],
    :path => 'people',
    :controller => 'learning_spaces/people'
    match '/checkout', to: 'learning_spaces/checkout#edit', :via => :get
    match '/checkout', to: 'learning_spaces/checkout#update', :via => :put
    
  end

  match '*a', :to => 'errors#routing'

  

end

app/models/organization.rb
class Organization < ActiveRecord::Base
 
  # Associations
  has_many :users
  has_many :learning_spaces

  has_one    :account, :as => :accountable
  accepts_nested_attributes_for :account
  
  # Paperclip
  has_attached_file :logo, 
                    :styles => { :medium => "140x140>", :thumb => "35x35>" },
                    :default_url => '/assets/logos/default_:style.png',
                    :path => "/avatars/:style/:id/:filename",
                    :s3_permissions => :public_read
  
  # Accesible
  attr_accessible :name, :logo, :account_attributes
  
  # Callbacks
  before_create    :create_id_hash 
  before_create    { self.build_account }

  # Validations
  validates      :name, presence: true, length: { maximum: 50 }


  ##############################################################
  # Public interface
  ##############################################################
  
  def to_param
    id_hash
  end
    
  ##############################################################
  # Private interface
  ##############################################################
  private
  
  def create_id_hash
    self.id_hash = Digest::SHA2.hexdigest( self.name )[0..6]
  end 
end

app/controllers/organizations/people_controller.rb
class Organizations::PeopleController < ApplicationController
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  
  def show
    @organization = Organization.find_by_id_hash( params[:id] )
    @learning_spaces = @organization.learning_spaces.all
  end

  def edit
    @organization = Organization.find_by_id_hash( params[:id] )
    @account = @organization.account
  end

  def update
    organization = current_user.organization
    learning_space = organization.learning_spaces.first
    redirect_to learning_space_path( organization, learning_space ) 
  end
end

app/helpers/organizations/people_helper.rb
module Organizations::PeopleHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/edit.html.erb
<%= simple_form_for( @organization, :html => { :class => 'form-horizontal' }) do |f| %>

<legend>Konto</legend>
<%= image_tag @organization.logo.url( :medium ), :class => 'controls' %> 
<div class="clear"></div><br>
<%= f.input :logo, :label => 'Logo' , class: 'btn' %>
<%= f.input :name, :label => 'Organisation', :disabled => true  %> 
<legend>Oplysninger</legend>

<legend>Invoices</legend>
<%= f.simple_fields_for :account do |a| %>
  <% a.object.orders.each do |order| %>  
  <div class="controls"><%= link_to order.updated_at.strftime('%d. %B %Y'), order_path( order ) %><br></div>
  <% end %>
<% end %>
<div class="form-actions">
    <%= f.button :submit, "Gem", class: 'btn' %><br><br>
  </div>

<% end %>

app/views/organizations/show.html.erb
<% if user_signed_in? %>
  <% if current_user.role? :user %>
    <%= render 'organizations/partials/user' %>
  <% elsif current_user.role? :admin %>
    <%= render 'organizations/partials/admin' %>
  <% end %>
<% end %>